{% set name = "opentelemetry-instrumentation-requests" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ae9495e6ff64e27bdb839fce91dbb4be56e325139828e8005f875baf41951a2e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation ==0.58b0
    - opentelemetry-semantic-conventions ==0.58b0
    - opentelemetry-util-http ==0.58b0
  run_constrained:
    - requests >=2.0,<3

test:
  source_files:
    - tests
  imports:
    - opentelemetry.instrumentation.requests
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - requests >=2.0,<3
    - pytest

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-requests
  summary: OpenTelemetry requests instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing HTTP requests made by the requests library.
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-requests
  doc_url: 

extra:
  recipe-maintainers:
    - mariusvniekerk
