{% set name = "opentelemetry-instrumentation-requests" %}
{% set version = "0.28b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-requests-{{ version }}.tar.gz
  sha256: 2480a03b9e0f001a22b9eca53770174f6eee5c85561c9cc590948cb3eaa48511

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.28b0
    - opentelemetry-semantic-conventions ==0.28b0
    - opentelemetry-util-http ==0.28b0
    - python >=3.6
    # - requests ~=2.0
    # - opentelemetry-test ==0.24b0
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.26b1
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.27b0
    # - httpretty ~=1.0
    # - requests ~=2.0
    # - opentelemetry-test-utils ==0.28b0
    # - httpretty ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-requests
  summary: OpenTelemetry requests instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
